### ISSUE TITLE
Voting system without Tallying Authority

### ISSUE THREAD

**Issue by bhack** [Movimento5StelleLazio/PEOCertificationServer#23]
https://blogs.ncl.ac.uk/security/2014/08/30/every-vote-counts-ensuring-integrity-in-large-scale-electronic-voting/

http://erc.europa.eu/erc-stories/towards-next-generation-e-voting

**Comment by bhack** [comment]
cc: @ilbarillo2014

**Comment by Emasoft** [comment]
@bhack Thank you. I'm still not sure that this new protocol is secure enough to replace public vote verification (I admit that seems very promising), but it is certainly much better than the Helios system for the generation of vote receipts. I think it would be ok to adopt it for the Parelon digital receipts. Receipts are very important to avoid too many false "hacked vote" claims, even if you cannot trust those  completely.

**Comment by bhack** [comment]
You can find other material of DRE-I in a college classroom experimentation:
http://homepages.cs.ncl.ac.uk/feng.hao/files/ClassroomVoting-final.pdf
https://evoting.ncl.ac.uk

See also Open Vote Network of the same author:
http://homepages.cs.ncl.ac.uk/feng.hao/home.php

**Comment by bhack** [comment]
And this is there reference of the EU financing page of the Feng project:
http://cordis.europa.eu/project/rcn/106591_en.html
